class gitlab::config (
  $external_url                                      = $::gitlab::external_url,
  $git_data_dir                                      = $::gitlab::git_data_dir,
  $postgresql_enable                                 = $::gitlab::postgresql_enable,
  $dir                                               = $::gitlab::dir,
  $log_directory                                     = $::gitlab::log_directory,
  $environment                                       = $::gitlab::environment,
  $internal_api_url                                  = $::gitlab::internal_api_url,
  $uploads_directory                                 = $::gitlab::uploads_directory,
  $rate_limit_requests_per_period                    = $::gitlab::rate_limit_requests_per_period,
  $rate_limit_period                                 = $::gitlab::rate_limit_period,
  $gitlab_host                                       = $::gitlab::gitlab_host,
  $gitlab_port                                       = $::gitlab::gitlab_port,
  $gitlab_https                                      = $::gitlab::gitlab_https,
  $gitlab_email_from                                 = $::gitlab::gitlab_email_from,
  $gitlab_support_email                              = $::gitlab::gitlab_support_email,
  $gitlab_default_projects_limit                     = $::gitlab::gitlab_default_projects_limit,
  $gitlab_default_can_create_group                   = $::gitlab::gitlab_default_can_create_group,
  $gitlab_username_changing_enabled                  = $::gitlab::gitlab_username_changing_enabled,
  $gitlab_default_theme                              = $::gitlab::gitlab_default_theme,
  $gitlab_signup_enabled                             = $::gitlab::gitlab_signup_enabled,
  $gitlab_default_projects_features_issues           = $::gitlab::gitlab_default_projects_features_issues,
  $gitlab_default_projects_features_merge_requests   = $::gitlab::gitlab_default_projects_features_merge_requests,
  $gitlab_default_projects_features_wiki             = $::gitlab::gitlab_default_projects_features_wiki,
  $gitlab_default_projects_features_wall             = $::gitlab::gitlab_default_projects_features_wall,
  $gitlab_default_projects_features_snippets         = $::gitlab::gitlab_default_projects_features_snippets,
  $gitlab_default_projects_features_visibility_level = $::gitlab::gitlab_default_projects_features_visibility_level,
  $issues_tracker_redmine                            = $::gitlab::issues_tracker_redmine,
  $issues_tracker_redmine_title                      = $::gitlab::issues_tracker_redmine_title,
  $issues_tracker_redmine_project_url                = $::gitlab::issues_tracker_redmine_project_url,
  $issues_tracker_redmine_issues_url                 = $::gitlab::issues_tracker_redmine_issues_url,
  $issues_tracker_redmine_new_issue_url              = $::gitlab::issues_tracker_redmine_new_issue_url,
  $issues_tracker_jira                               = $::gitlab::issues_tracker_jira,
  $issues_tracker_jira_title                         = $::gitlab::issues_tracker_jira_title,
  $issues_tracker_jira_project_url                   = $::gitlab::issues_tracker_jira_project_url,
  $issues_tracker_jira_issues_url                    = $::gitlab::issues_tracker_jira_issues_url,
  $issues_tracker_jira_new_issue_url                 = $::gitlab::issues_tracker_jira_new_issue_url,
  $gravatar_enabled                                  = $::gitlab::gravatar_enabled,
  $gravatar_plain_url                                = $::gitlab::gravatar_plain_url,
  $gravatar_ssl_url                                  = $::gitlab::gravatar_ssl_url,
  $ldap_enabled                                      = $::gitlab::ldap_enabled,
  $ldap_host                                         = $::gitlab::ldap_host,
  $ldap_base                                         = $::gitlab::ldap_base,
  $ldap_port                                         = $::gitlab::ldap_port,
  $ldap_uid                                          = $::gitlab::ldap_uid,
  $ldap_method                                       = $::gitlab::ldap_method,
  $ldap_bind_dn                                      = $::gitlab::ldap_bind_dn,
  $ldap_password                                     = $::gitlab::ldap_password,
  $ldap_allow_username_or_email_login                = $::gitlab::ldap_allow_username_or_email_login,
  $ldap_user_filter                                  = $::gitlab::ldap_user_filter,
  $ldap_group_base                                   = $::gitlab::ldap_group_base,
  $satellites_path                                   = $::gitlab::satellites_path,
  $backup_path                                       = $::gitlab::backup_path,
  $backup_keep_time                                  = $::gitlab::backup_keep_time,
  $gitlab_shell_path                                 = $::gitlab::gitlab_shell_path,
  $gitlab_shell_repos_path                           = $::gitlab::gitlab_shell_repos_path,
  $gitlab_shell_hooks_path                           = $::gitlab::gitlab_shell_hooks_path,
  $gitlab_shell_upload_pack                          = $::gitlab::gitlab_shell_upload_pack,
  $gitlab_shell_receive_pack                         = $::gitlab::gitlab_shell_receive_pack,
  $gitlab_shell_ssh_port                             = $::gitlab::gitlab_shell_ssh_port,
  $git_bin_path                                      = $::gitlab::git_bin_path,
  $git_max_size                                      = $::gitlab::git_max_size,
  $git_timeout                                       = $::gitlab::git_timeout,
  $db_adapter                                        = $::gitlab::db_adapter,
  $db_encoding                                       = $::gitlab::db_encoding,
  $db_database                                       = $::gitlab::db_database,
  $db_pool                                           = $::gitlab::db_pool,
  $db_username                                       = $::gitlab::db_username,
  $db_password                                       = $::gitlab::db_password,
  $db_host                                           = $::gitlab::db_host,
  $db_port                                           = $::gitlab::db_port,
  $db_socket                                         = $::gitlab::db_socket,
){

  file {
    '/etc/gitlab':
      ensure => directory,
  }

  file {
    '/etc/gitlab/gitlab.rb':
      ensure  => present,
      content => template('gitlab/gitlab.rb.erb'),
      mode    => '0600',
      require => File['/etc/gitlab'],
      notify  => Exec['gitlab-reconfigure'],
  }

}
